apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: manual-nfs-pvc
  labels:
    storage.k8s.io/name: nfs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ''  # empty string otherwise default storage class is used
  volumeName: manual-nfs-pv
  resources: 
    requests:
      storage: 1Gi